import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./homeGlobals.css";
import Navbar from "@/components/client/Navbar";
import Navheader from "@/components/client/Navheader";
import Navbody from "@/components/client/Navbody";
import StickyTest from "@/components/client/demo";
import Footer from "@/components/client/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} text-primary-300 font-sans antialiased`}
      >
        <Navheader />
        <Navbody />
        <div className="relative">
          <Navbar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
